import type { Metadata } from 'next';
import { GeistSans } from '@vercel/geist/sans';
import { GeistMono } from '@vercel/geist/mono';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body>タグのclassNameにそれぞれのフォントのvariableプロパティを適用します */}
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
